
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module exp9_2(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,


	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS

	
);


//=======================================================
//  REG/WIRE declarations
//=======================================================

assign VGA_SYNC_N = 0;

picture p(CLOCK_50,1'b0,1'b1,VGA_HS,VGA_VS,VGA_BLANK_N,VGA_CLK,VGA_R,VGA_G,VGA_B);


//=======================================================
//  Structural coding
//=======================================================



endmodule
