
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module exp4_2(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		     [9:0]		LEDR
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
//wire signal;
//divider#(2) d(CLOCK_50,signal);
//assign LEDR[0] = signal;用于验收

s_reset SD(CLOCK_50,SW[0],SW[1],LEDR[9]);
a_reset AD(CLOCK_50,SW[0],SW[1],LEDR[8]);


//=======================================================
//  Structural coding
//=======================================================



endmodule
